### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by yannisgu** [allestuetsmerweh/sportident.js#28]
**Is your feature request related to a problem? Please describe.**
I would like to use sporident.js in one of my projects and I would be easier to get started if there would be an NPM package.

**Describe the solution you'd like**
Publish a NPM package to npmjs.com

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by allestuetsmerweh** [comment]
Hi, excited to see that people can make use of this package.

I quickly published this package as-is, didn't test it or anything. Hope it works.

Please note that I'm currently refactoring this to TypeScript and that the interfaces (so far especially in the `storage` module) might change significantly.

**Comment by allestuetsmerweh** [comment]
NPM package is broken as of now
