### ISSUE TITLE
NodeJS support

### ISSUE THREAD

**Issue by yannisgu** [allestuetsmerweh/sportident.js#31]
# Is your feature request related to a problem? Please describe.

I would like to use the library in NodeJS context. However there are couple of issues which lead the library to not be compatible.

## Webpack Target
Currently webpack is used to transpile the library, however with web target. The output is then not usable from nodeJS.

## NodeJS Driver
Currently sportident.js supports WebUSB, however should access the serial port with native libraries. 

# Describe the solution you'd like

## Webpack Target
There are different options to solve this issue: 
- Do not use webpack at all and instead use directly babel/tsc to transpile each file into  ES5 compatible files. This would assume that all web-consumers of sportident.js would use something like webpack to pack everything web-compatible. NodeJS would't use this.
- Additionally to si.min.js add a target si.node.js. This would mean to add a configuration to webpack.config.js to create an additional output.

## NodeJS Driver
I would propose to create an additional driver based on `serialport` (https://serialport.io/).
Maybe this should be packaged into an own module, to prevent any issues, having a dependency to serialport in a web-only usage.

**Describe alternatives you've considered**
n/a

**Additional context**
My use case is to have a tool reading "auto-send" punches and writing them into a live-system.

**Comment by allestuetsmerweh** [comment]
Concerning the build target, feel free to change anything, as long as the testbench can still run. I assume this needs to be done first.
