### ISSUE TITLE
Question about time / timestamp

### ISSUE THREAD

**Issue by guizmo51** [allestuetsmerweh/sportident.js#69]
Hi, I try to understand how works the time/timestamp in your library. 
Per example I receive : 
start : 61166
178:  46735

I don't remember (I lost the precious doc I had about SportIdent algorithm) how work the time/timestamp and probably what is done by your library between. Can you explain me ? thanks !

**Comment by allestuetsmerweh** [comment]
So first of all, there was a bug until recently, where the endianness of the time was wrong. Maybe that's the problem for you.
Then, there's also (for newer SiCards) some information about the weekday (which I did not implement AFAIK); maybe this helps: https://github.com/krooks/qsilib/blob/master/lib/siproto.cpp#L103

**Comment by guizmo51** [comment]
Ok, Just updated and I will check it. 
Sometimes (randomly) while reading out I have a "strange Response: expected F0, but got E7..." . The siCardInserted is triggered but the read() got in catch. Do you know why ? (If you prefer I can open a new issue in order to get a better tracking of this issue)

**Comment by allestuetsmerweh** [comment]
Thank you. This means that the target multiplexer was expecting a response to a SET_MS command, but instead, you removed the SiCard. I guess figuring out these edge cases will be really hard, but I will try to find a solution for these async commands that are triggered by the device.

**Comment by allestuetsmerweh** [comment]
opened #70

**Comment by guizmo51** [comment]
OK, I juste updated but nothing changes. something is wrong in the timing. In my example (in my current SiCard, times goes wrong from control 164 until the end.. I will check the raw data (in sicard and check) and try help !


![Capture d’écran 2019-12-17 à 15 20 02](https://user-images.githubusercontent.com/2675497/71003558-63a96e00-20e1-11ea-899c-c92f406827ba.png)
![Capture d’écran 2019-12-17 à 15 18 50](https://user-images.githubusercontent.com/2675497/71003524-5e4c2380-20e1-11ea-9d09-3b5f5b2c081f.png)

**Comment by allestuetsmerweh** [comment]
Nah, the problem is basically an integer overflow. This framework at the time uses just 2 bytes for time => can represent 65536 seconds, but a day has 86400 seconds. So twice a day the time goes back to zero. I will update the framework to give more useful data. I have all the information to do so.

**Comment by allestuetsmerweh** [comment]
Pull request is out. Feel free to review/comment

**Comment by allestuetsmerweh** [comment]
Release `v2.0.0-alpha.2` fixes these issues.

**Comment by guizmo51** [comment]
Ok I'm working on a PR dealing with the byte about AM/PM. I will send my PR when it will be ok
