### ISSUE TITLE
"Strange response" logged even in plausible scenarios

### ISSUE THREAD

**Issue by allestuetsmerweh** [allestuetsmerweh/sportident.js#70]
**Describe the bug**
The log e.g. says `strange Response: expected F0, but got E7` (expected `SET_MS`, but got `SI_REM`).

**To Reproduce**
Just read a lot of cards, it will happen at some point.

**Expected behavior**
This scenario is perfectly OK; the target multiplexer should just forward the `SI_REM` (or any other device-initiated command like `SI5_DET`) to the current target (or the direct target; consider the edge cases)

**Comment by guizmo51** [comment]
Ok Now with new release I got "Uncaught (in promise) Error: contradicting SET_MS response" from SiTargetMultiplexer" , Something is probably wrong in my way of opening and reading ?  Or this exception is "normal" and I need to relaunch the reading ?

**Comment by allestuetsmerweh** [comment]
That is an exception shat should not occur. It means you sent to the device a request to change the operating mode, but the response it sends says that it changed the operating mode to something else than what you requested... 

I cannot reproduce this problem in the testbench. Is your code public? Do you have two devices connected at the same time? Do you have two SiTargetMultiplexers for one SiDevice?

**Comment by guizmo51** [comment]
My code is here : https://gist.github.com/guizmo51/3f11a15b68b516eb0efd792b50bf95a3 
No I have only one device.

**Comment by allestuetsmerweh** [comment]
I have no idea what that could be...
Does it occur often?
Do you have any logs you could share?

**Comment by guizmo51** [comment]
It occurs for the first read. Scénario : 
I enable the SIStation and listening for SiCardInserted, I punch a Card and it triggers this error (contradicting SET_MS response (in SiTargetMultiplexer). Maybe I initialized the SiDevice with the wrong way ?

**Comment by allestuetsmerweh** [comment]
I'm pretty sure that if you send an outgoing request (like `this.station.setCode(10)` or similar) before receiving events from the card (`this.station.addEventListener(...)`), this issue would not appear. It's a hack, but the investigation will take longer.

**Comment by allestuetsmerweh** [comment]
Issue: #83 
PR: #84
