### ISSUE TITLE
Time should not reset to zero within one SiCard

### ISSUE THREAD

**Issue by allestuetsmerweh** [allestuetsmerweh/sportident.js#71]
**Describe the bug**
Sometimes, the punch times don't increase monotonically. This is because of integer overflow.

**To Reproduce**
Go to the shell and do `test card` it occurs when the time exceeds `43200`.

**Expected behavior**
Postprocess SiCards to have clearTime <= checkTime <= startTime <= punch n time <= punch n+1 time <= finishTime

**Comment by guizmo51** [comment]
I tried the last version (alpha 2), the cleartime is missing and the issue still occurs (reset after noon) I will try to understand why. Of course for the last point I can do a patch on my app. Do you know why the date is not available ? I thought it was a timestamp and the date was available

**Comment by allestuetsmerweh** [comment]
Clear time is only available in SiCard6. 
You need to do something like:
```
...
    s.siCard.read().then((d) => {
      const raceResult = d.getNormalizedRaceResult();
      // display raceResult to the user.
    });
...
```

**Comment by guizmo51** [comment]
Ok I got it (weird time because of old start time ) 
I don't understand why the timestamp is not available (I thought the SiStation writes timestamp on sicard). I think there's a missunderstand and I think this is a need (because in some case you have no start time) and you just want to get the date and time of punch (like SIConfig features)

**Comment by allestuetsmerweh** [comment]
> because in some case you have no start time

In case you have no start time on the SiCard:
```
const startTimeFromDb = // retrieve start time from the start time database (the organizer knows when the runner started)
const raceResultWithStart = {...card.raceResult, startTime: startTimeFromDb};
const normalizedRaceResult = makeStartZeroTime(monotonizeRaceResult(raceResultWithStart))

```
