### ISSUE TITLE
Target multiplexer cannot handle some device-initiated cases

### ISSUE THREAD

**Issue by allestuetsmerweh** [allestuetsmerweh/sportident.js#83]
**Describe the bug**

**To Reproduce**
- Don't send any command to the `SiMainStation`, just add a `cardInserted` callback
- In the callback, read the card
- Run the program and insert a card
=> "Uncaught (in promise) Error: contradicting SET_MS response"

**Expected behavior**
The card is being read.

**Comment by guizmo51** [comment]
Ok I just received my BSM, I will try when the ne update will be available with npm.

**Comment by allestuetsmerweh** [comment]
Did some testing today and released: https://github.com/allestuetsmerweh/sportident.js/releases/tag/v2.0.0-alpha.3

**Comment by guizmo51** [comment]
Unfortunately this issue still occurs but I have an other response "Error: SiStorage.splice must preserve the size of the storage data (1024 -> 899)"
Scenario (for the first punch only, everything is, I think, well configured and I have "beep via confirm()" when punch is OK 
- I punch
- Si Card is still inserted, I can stay with SIcard inserted no beep, no confirmation , the "siCardInserted" is well triggered.
- I decide to remove the SiCard and I have the "Error: SiStorage.splice must preserve the size of the storage data (1024 -> 899)" issue.

**Comment by allestuetsmerweh** [comment]
You're probably using a type of SiCard I don't own. Is it a SIAC?

**Comment by guizmo51** [comment]
Yes it's a SIAC. Do you want an export of row (hex) data ?

**Comment by allestuetsmerweh** [comment]
> Do you want an export of row (hex) data ?
That would be great. Maybe just the console output? https://stackoverflow.com/a/31059700

**Comment by guizmo51** [comment]
hey, I'm a web developer I know to export console output ;-) 
But do you prefer content of SICard or console output with issue ?

**Comment by allestuetsmerweh** [comment]
> hey, I'm a web developer I know to export console output ;-)

No offense ;) I'm also thinking about how to best send bug reports like these... If you have an idea, let me know.

>  But do you prefer content of SICard or console output with issue ?

Best would be to have both, but just the console output would already help greatly.

**Comment by guizmo51** [comment]
I found my SICard9 too and tried with it. I also got error on first reading. Per example : first read SIAC => 
issue second read (SIAC or other sicard) will be OK. 
The same is I replace the SIAC by the SI9. Logs in attachment. I will provide content of sicard asap.


[console-sicard9.log](https://github.com/allestuetsmerweh/sportident.js/files/4019307/console-sicard9.log)
[console-siac.log](https://github.com/allestuetsmerweh/sportident.js/files/4019309/console-siac.log)

**Comment by allestuetsmerweh** [comment]
Hmmm, unfortunately, I cannot see the `console.debug` outputs of the SiDevice (the data that was sent over USB wire) in those logs... Are debug messages excluded from console exports?

**Comment by guizmo51** [comment]
with console.debug 
[localhost-1578063584932.log](https://github.com/allestuetsmerweh/sportident.js/files/4019537/localhost-1578063584932.log)

**Comment by allestuetsmerweh** [comment]
I can not understand what's happening there. A GET_SI8 command is sent, but the station just does not respond... I assume your station is not configured correctly.

I wrote a convenience function on SiMainStation to configure it to read cards, please refer to the example app (pull request not merged yet): https://github.com/allestuetsmerweh/sportident.js/pull/92/files#diff-41fdff9264cef48019ca7570a9272a7aR15

**Comment by guizmo51** [comment]
Yes I read your example, Ok I will try with the next update and when I will have more free time ;-)
Thanks !

**Comment by guizmo51** [comment]
Can you, please, generate the alpha 4 on npm ? thanks !

**Comment by allestuetsmerweh** [comment]
whoops. here you go.
