### ISSUE TITLE
Storage locations might be wrong

### ISSUE THREAD

**Issue by allestuetsmerweh** [allestuetsmerweh/sportident.js#85]
**To Reproduce**
1. Run testbench
2. simulate a station
3. simulate e.g. a SiCard10
=> What SiConfig+ reads differs somewhat from what's there in the siCard10Examples

**Expected behavior**
Storage locations are correct, i.e. the same as SiConfig+ reads.

**Comment by guizmo51** [comment]
Can you share the SiConfig+ result and the SiCard10 result (using your lib) ?

**Comment by allestuetsmerweh** [comment]
I realize it's mostly reading `61166` (that's `0xEEEE`) instead of stating that it is null...
Also, SiConfig+ does not support the checkTime of SiCard5, but I tested it and it's there. (I have an SiCard5 and an SiCard10)
